### ISSUE TITLE
Deleting a transaction should restore the amount in the wallet

### ISSUE THREAD

**Issue by vagnerwentz** [vagnerwentz/visualizesse#7]
When you delete a transaction, the amount is not being added to the balance.

- [x] The balance should increase when the transaction is deleted.

**Comment by whoiswentz** [comment]
You should never delete a transaction, instead you can update its state to a invalid one

**Comment by vagnerwentz** [comment]
> You should never delete a transaction, instead you can update its state to a invalid one

Good idea, but I thought something that as we know, nowadays we are not transferring the money we are registering the transaction the user did just to control his personal finance.

But you gave a ideia that we could have a page or tab page that the user is able to see the `canceled`/`inactive` transactions as with bankings apps.
